<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\AFMReforge.Core\AFMReforge.Core.csproj" />
    <ProjectReference Include="..\..\shared\AFMDataClientCore\src\AFMDataClient.Core\AFMDataClient.Core.csproj" />
  </ItemGroup>
</Project>
